import Location from '../../src/model/location'

let output = new Location({ 
    name: 'Statue of Liberty', 
    id: '5a0d7e67078e35af0c456a277df9ffba7c1e4da6',
    lat: 40.6892494,
    long: -74.04450039999999,
    addess: 'New York, NY 10004, USA'
})

let arrayWith4Items = [
    "Statue of Liberty", 
    "Nova Iorque, NY 10038, EUA",
    "88 Pine St, New York, NY 10005, EUA",
    "60 Front St, Hempstead, NY 11550, EUA"
];

let arrayWithMoreThan100 = [ 
    "Statue of Liberty", 
    "Nova Iorque, NY 10038, EUA",
    "88 Pine St, New York, NY 10005, EUA",
    "60 Front St, Hempstead, NY 11550, EUA",
    "Alamo",
    "Alhambra",
    "Andros Island",
    "Angel Falls",
    "Angkor Wat, Cambodia",
    "Atlantic City Boardwalk",
    "Ayers Rock",
    "Big Ben",
    "Bora Bora",
    "British Museum",
    "Canals of Amsterdam",
    "Cathedral of Seville",
    "Cave of Crystals",
    "Christ the Redeemer",
    "Cinque Terre National Park",
    "Colosseum",
    "Crater Lake",
    "Dead Sea",
    "Death Valley",
    "Devil's Tower",
    "Dome of the Rock",
    "Easter Island",
    "Edinburgh Castle",
    "Eiffel Tower",
    "Empire State Building",
    "The Forbidden City, China",
    "French Quarter",
    "Galapagos Islands",
    "Gateway Arch",
    "Gettysburg Battlefield",
    "Glacier Bay Basin",
    "Glacier National Park",
    "Glowworm Cave",
    "Golden Gate Bridge",
    "Grand Canal",
    "The Grand Canyon",
    "Grand Mosque in Mecca",
    "Great Barrier Reef",
    "Great Mosque of Cordoba",
    "Great Wall of China",
    "Hagia Sophia",
    "Hawaii Volcanoes National Park",
    "Hollywood Boulevard",
    "Iguazu Falls",
    "Kiyomizu Dera",
    "Kremlin",
    "Lake Titicaca",
    "Las Ramblas","Las Vegas Strip",
    "The Leaning Tower of Pisa", 
    "Louvre Museum", 
    "Machu Picchu", 
    "Matterhorn", 
    "Mayan Pyramids of Chichen Itza", 
    "Metropolitan Museum of Art", 
    "Mount Everest", 
    "Mount Fuji", 
    "Mount Kilimanjaro", 
    "Mount Rushmore", 
    "Napa Valley", 
    "Ngorongoro Crater",
    "Niagara Falls", 
    "Notre Dame Cathedral", 
    "Pacific Rim National Park", 
    "Pebble Beaches of Nice", 
    "Petra", 
    "Petronas Twin Towers", 
    "Portland Head Lighthouse", 
    "Puerta Del Sol", 
    "Pyramids of Giza", 
    "Redwood National Park", 
    "Rock of Gibraltar", 
    "Rocky Mountain National Park, U.S.", 
    "Ruins of Athens", 
    "Ruins of Pompeii", 
    "Sagrada Familia", 
    "Willis Tower (Sears Tower)", 
    "Sedlec Ossuary", 
    "Sistine Chapel", 
    "Smithsonian Institution", 
    "Space Needle", 
    "St. Peter's Basilica", 
    "Statue of Liberty", 
    "Stonehenge", 
    "Sydney Opera House", 
    "Taj Mahal", 
    "Temple of the Golden Pavilion", 
    "Teotihuacan", 
    "Tian Tan Buddha", 
    "Times Square", 
    "Varanasi", 
    "Victoria Falls", 
    "Wailing Wall", 
    "Walt Disney World Resort", 
    "The Washington Monument", 
    "White Cliffs of Dover", 
    "White House", 
    "Winchester Cathedral", 
    "Yosemite National Park", 
    "Zion National Park"
]

export { output, arrayWith4Items, arrayWithMoreThan100 };